### ISSUE TITLE
[Feature] Add author's description

### ISSUE THREAD

**Issue by bakermeoe** [nyancodeid/quotes#114]
Great project ! Simple but elegant ! @nyancodeid 

I wonder whether we could add new author's description and show it on the card ? So everybody who reads the quotes also knows who/what is the author's job (CEO of xxx, Founder of xxx, etc.) ?

**Comment by nyancodeid** [comment]
Good idea @richardoey , but I wonder who the author is referring to here. The author who said the quote or the author who brought the quote here.

**Comment by mushonnip** [comment]
> Good idea @richardoey , but I wonder who the author is referring to here. The author who said the quote or the author who brought the quote here.

I think the quote author (who said) because we need to know his background

**Comment by richardoey** [comment]
> I think the quote author (who said) because we need to know his background

Yes, the quote's author. Maybe using smaller font than the quote's author name, and brief but precise. Sorry I can't send a picture or draft design now. I raised the feature request to know maybe other has the same insight. I think this needs to add more key,value data in the YAML file.

**Comment by nyancodeid** [comment]
> > I think the quote author (who said) because we need to know his background
> 
> Yes, the quote's author. Maybe using smaller font than the quote's author name, and brief but precise. Sorry I can't send a picture or draft design now. I raised the feature request to know maybe other has the same insight. I think this needs to add more key,value data in the YAML file.

Yep, i agree with you, we can add `author description` as an optional information. Because there are some quotes hard to be describe the author background, and we don't wanna lose the quotes meaning.

**Comment by richardoey** [comment]
> > > > I think the quote author (who said) because we need to know his background
> > > 
> > > 
> > > Yes, the quote's author. Maybe using smaller font than the quote's author name, and brief but precise. Sorry I can't send a picture or draft design now. I raised the feature request to know maybe other has the same insight. I think this needs to add more key,value data in the YAML file.
> > 
> > 
> > but i think it makes more space in the card. how about adding a link (to wikipedia or something) to author's name just like we linked our github profile
> 
> I think so, we lose simplicity if we add more additional information into quotes card.

Agree. I also think it will be complicated if the author description is too long or taking too much space. Giving additional link is the best approach for now I think
