### ISSUE TITLE
Blurry download result

### ISSUE THREAD

**Issue by ngekoding** [nyancodeid/quotes#144]
Just trying to download the quote image, but it showed as a blurred image!

Please look at this:

![quotes-nyandev-id-1633915036734](https://user-images.githubusercontent.com/11625690/136720643-4e6c3c7e-41f8-4dd6-b454-c1d288c7b915.png)

**Comment by nyancodeid** [comment]
Maybe because of scale. I can see library related issue here

https://github.com/tsayen/dom-to-image/issues/69#issuecomment-486146688

**Comment by nyancodeid** [comment]
Let's try this solution

https://github.com/tsayen/dom-to-image/issues/69#issuecomment-732448518
