### ISSUE TITLE
Add hover effect on quote filter

### ISSUE THREAD

**Issue by azizramdan** [nyancodeid/quotes#188]
I think it would be better to add some effects when hovering over the quote filter

https://user-images.githubusercontent.com/27954794/137631430-e7885fd0-764c-4186-b962-67739cf1a65c.mp4

**Comment by azizramdan** [comment]
How about this? @nyancodeid 

![image](https://user-images.githubusercontent.com/27954794/137656257-9613641e-16e7-41a5-a526-b644924cd440.png)

![image](https://user-images.githubusercontent.com/27954794/137656271-9d42eb05-875a-4df0-a596-a21563586354.png)

**Comment by nyancodeid** [comment]
> How about this? @nyancodeid 
> 
> ![image](https://user-images.githubusercontent.com/27954794/137656257-9613641e-16e7-41a5-a526-b644924cd440.png)
> 
> ![image](https://user-images.githubusercontent.com/27954794/137656271-9d42eb05-875a-4df0-a596-a21563586354.png)
> 

Awesome, it's look pretty good now. Good job @azizramdan

**Comment by nyancodeid** [comment]
Merged, i gonna close this issues. Thanks @azizramdan
