### ISSUE TITLE
Synchronization between searches and favorite quotes

### ISSUE THREAD

**Issue by azizramdan** [nyancodeid/quotes#277]
What should be the behavior for this cases?

Case 1
When we do a search on all quotes (not favorites), then switch favorite quotes, then switch back to all quotes, it will show all quotes instead of filtered quotes even search keyword exists
https://github.com/nyancodeid/quotes/blob/2663e50b79aaff1571fd35316bd04e7ebbfb04c1/src/views/QuoteGallery.vue#L100

Case 2
When we do a search on all quotes, then switch favorite quotes, it will show all favorite quotes instead of filtered favorite quotes even search keyword exists
https://github.com/nyancodeid/quotes/blob/2663e50b79aaff1571fd35316bd04e7ebbfb04c1/src/views/QuoteGallery.vue#L92-L94

https://user-images.githubusercontent.com/27954794/139153810-fe1914e2-9977-468a-b4df-c6bf3c188d11.mp4

**Comment by nyancodeid** [comment]
> How about for each (all quotes & favorites) have it own search keyword to use?
> 
> Base on which feature currently active. Like if we are already search for "test" on all quotes, then when switching to favorites, the search keyword get empty, but when back to all quotes, the "test" keyword automatically filled.

That's interesting, maybe we can use this solution.

**Comment by nyancodeid** [comment]
Closed with PR #294
