### ISSUE TITLE
Better empty message for favorite quotes

### ISSUE THREAD

**Issue by ngekoding** [nyancodeid/quotes#298]
I think we must have a different empty message for **favorite quote**. The current empty message unrelated with the favorite feature, and currently we don't search anything.

For example:

**Anda belum memiliki quote favorit, …**

![Empty](https://user-images.githubusercontent.com/11625690/139655870-7a3e52fd-297e-4061-9bd6-e017b2ba66a4.png)

**Comment by nyancodeid** [comment]
That would be great, I'll add it to the PR #294

Thank you for suggestion @ngekoding

**Comment by ngekoding** [comment]
It is my pleasure

**Comment by nyancodeid** [comment]
Closed with PR #294
