### ISSUE TITLE
haloo

### ISSUE THREAD

**Issue by fiqryq** [nyancodeid/quotes#313]
halo mas @nyancodeid sekarang aku lg belajar web programming aku iseng buat app ini [wallofresolution](https://github.com/fiqryq/wall-of-resolution) inspirasinya dari app quote mas @nyancodeid dan aku mau izin pake palet gradienttnya punya mas karena blm bisa buat pallet gitu hehe. Terimakasih sebelumnya

**Comment by nyancodeid** [comment]
Halo juga mas @fiqryq, boleh mas silahkan. Btw keren banget ide nya. 🥳

**Comment by fiqryq** [comment]
Tengkyu mass
